before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    main: ./main.go
    binary: kubemq
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - 386
      - amd64
      - arm64
      - arm
    goarm:
      - 5
      - 6
      - 7
    ldflags:
      - "-X 'main.version={{.Env.VERSION}}'"
    ignore:
      - goos: windows
        goarch: 386
      - goos: darwin
        goarch: 386
archives:

  - replacements:
    id: tar
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - none*
#    format_overrides:
#      - goos: windows
#        format: zip
  - replacements:
    id: zip
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: zip
    files:
      - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
