api:
  port: 8888
authentication:
  config: ""
  enable: true
  jwtConfig:
    filePath: env_filePatch
    key: env-def-key
    signatureType: HS256
  type: ""
authorization:
  autoReload: 1000
  enable: true
  filePath: some-env-file-path
  policyData: some-env-data
  url: some-env-url
broker:
  diskSyncSeconds: 60
  maxConn: 2
  maxPayload: 2
  parallelRecovery: 2
  readBufferSize: 4
  sliceMaxAgeSeconds: 0
  sliceMaxBytes: 64
  sliceMaxMessages: 0
  writeBufferSize: 4
  writeDeadline: 2
grpc:
  bodyLimit: 2
  port: 3
  subBuffSize: 2
key: ""
license: ""
licenseFileName: ""
log:
  level: trace
queue:
  defaultVisibilitySeconds: 2
  defaultWaitTimeoutSeconds: 2
  maxDelaySeconds: 2
  maxExpirationSeconds: 2
  maxInflight: 2048
  maxNumberOfMessages: 2
  maxReceiveCount: 2
  maxVisibilitySeconds: 2
  maxWaitTimeoutSeconds: 2
  pubAckWaitSeconds: 60
rest:
  bodyLimit: b
  cors:
    allowCredentials: true
    allowHeaders:
    - a
    - b
    - c
    allowMethods:
    - a
    - b
    - c
    allowOrigins:
    - a
    - b
    - c
    exposeHeaders:
    - a
    - b
    - c
    maxAge: 2
  port: 2
  readTimeout: 2
  subBuffSize: 2
  writeTimeout: 2
routing:
  autoReload: 1000
  data: some-env-data
  enable: true
  filePath: some-env-file-path
  url: some-env-url
security:
  ca:
    data: b
    filename: b
  cert:
    data: b
    filename: b
  key:
    data: b
    filename: b
store:
  cleanStore: true
  maxMessages: 2
  maxPurgeInactive: 2
  maxQueueSize: 2
  maxQueues: 2
  maxRetention: 2
  maxSubscribers: 2
  storePath: b
